codecov:
  require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no
flags:
  integrationtests:
    paths:
      - CmsData
      - CmsWeb
      - ImageData
      - TransactionGateway
      - UtilityExtensions
  unittests:
    paths:
      - CmsData
      - CmsWeb
      - ImageData
      - TransactionGateway
      - UtilityExtensions
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
